POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "New Event3",
    "details": null,
    "maximumAttendees": 2
}

###

POST http://localhost:3333/events/d24ec8dc-b03f-4a01-ba2c-837c7fec0aa6/attendees
Content-Type: application/json

{
    "name": "Messias Ribeiro do Amaral",
    "email": "messiasamaral123@gmail.com"
}

###

GET http://localhost:3333/events/d24ec8dc-b03f-4a01-ba2c-837c7fec0aa6

###

GET http://localhost:3333/attendees/4/badge

###

GET http://localhost:3333/attendees/4/check-in

###

GET http://localhost:3333/events/d24ec8dc-b03f-4a01-ba2c-837c7fec0aa6/attendees